/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import com.sun.glass.events.KeyEvent;
import java.awt.Cursor;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.springframework.security.crypto.bcrypt.BCrypt;
/**
 *
 * @author Pramudya
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        this.btn_log.setOpaque(false);
        this.btn_log.setContentAreaFilled(false);
        this.btn_log.setBorderPainted(false);
        this.jToggleButton1.setBackground(new java.awt.Color(0,0,0,0));
         this.btn_lupapassword.setBackground(new java.awt.Color(0,0,0,0));
         this.btn_newakun.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_newakun = new javax.swing.JButton();
        btn_lupapassword = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        TextUsername = new javax.swing.JTextField();
        btn_log = new javax.swing.JButton();
        TextPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_newakun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newakunMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newakunMouseExited(evt);
            }
        });
        btn_newakun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newakunActionPerformed(evt);
            }
        });
        getContentPane().add(btn_newakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 120, 12));

        btn_lupapassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_lupapasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_lupapasswordMouseExited(evt);
            }
        });
        btn_lupapassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lupapasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lupapassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 90, 12));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close-eyeres.png"))); // NOI18N
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 40, 40));

        TextUsername.setBackground(new java.awt.Color(255, 255, 255));
        TextUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextUsername.setToolTipText("");
        TextUsername.setBorder(null);
        TextUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(TextUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 265, 250, 36));

        btn_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logActionPerformed(evt);
            }
        });
        getContentPane().add(btn_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 426, 130, 40));

        TextPass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TextPass.setBorder(null);
        TextPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPassActionPerformed(evt);
            }
        });
        getContentPane().add(TextPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 362, 210, 36));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/MainMenuLogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerateToken(){
        String rand = "abcdefghijklmnopqrstuvwxyz".toUpperCase();
        int range = (rand.length()) ;
        String Result = "";
        for (int i = 0; i < 6; i++) {
            int getValue = (int)(Math.random() * range);
            char CharPoss = rand.charAt(getValue);
            Result += CharPoss;
        }
        System.out.println(Result);
    }
    
    private void btn_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logActionPerformed
//         String getUsername = TextUsername.getText();
//        JOptionPane.showMessageDialog(rootPane, "tombol di klik, selamat datang " + getUsername);
//        new DashboardFrame().setVisible(true);
//        dispose();
             String userAkun = TextUsername.getText(),
                passAkun = TextPass.getText();
         
             try {
            String sql = "SELECT * FROM akun WHERE username = '" + userAkun + "' ";
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String namaAkun = r.getString("nama");
                String userAcount = r.getString("username");
                String passAcount = r.getString("pass");

                if (userAkun.equals(userAcount) && BCrypt.checkpw(passAkun, passAcount)) {
                    String upsql = "UPDATE session_login SET nama = '" + namaAkun + "' WHERE kode_sesi = 1";
                    s.executeUpdate(upsql);
                    System.out.println("berhasil masuk");
                    JOptionPane.showMessageDialog(this, "selamat datang " + namaAkun + " !!!");
                    new DashboardFrame().setVisible(true);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "password tidak cocok");
                }
            } else {
                JOptionPane.showMessageDialog(this, "username atau password salah");
                System.out.println("salahhh");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_logActionPerformed

    private void TextUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsernameActionPerformed

    private void TextPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPassActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        if(jToggleButton1.isSelected()){
            this.TextPass.setEchoChar((char)0);
            this.jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/eyeres.png")));
        }else{
            this.TextPass.setEchoChar('*');
            this.jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close-eyeres.png")));
        }
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btn_lupapasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lupapasswordActionPerformed
        new LupapassFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_lupapasswordActionPerformed

    private void btn_lupapasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lupapasswordMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_lupapasswordMouseEntered

    private void btn_lupapasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lupapasswordMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_lupapasswordMouseExited

    private void btn_newakunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newakunMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_newakunMouseEntered

    private void btn_newakunMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newakunMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_newakunMouseExited

    private void btn_newakunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newakunActionPerformed
        new RegistFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_newakunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TextPass;
    private javax.swing.JTextField TextUsername;
    private javax.swing.JButton btn_log;
    private javax.swing.JButton btn_lupapassword;
    private javax.swing.JButton btn_newakun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
