/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base;

import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.springframework.security.crypto.bcrypt.BCrypt;

/**
 *
 * @author Pramudya
 */
public class LupapassFrame extends javax.swing.JFrame {

    /**
     * Creates new form LupapassFrame
     */
    public LupapassFrame() {
        initComponents();
        this.text_username.setBackground(new java.awt.Color(0,0,0,0));
        this.text_token.setBackground(new java.awt.Color(0,0,0,0));
        this.text_passfield.setBackground(new java.awt.Color(0,0,0,0));
        this.jToggleButton1.setBackground(new java.awt.Color(0,0,0,0));
        this.btn_mulai.setBackground(new java.awt.Color(0,0,0,0));
        this.btn_back.setBackground(new java.awt.Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weakness = new javax.swing.JLabel();
        text_token = new javax.swing.JTextField();
        text_username = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        text_passfield = new javax.swing.JPasswordField();
        btn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_mulai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        weakness.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        weakness.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(weakness, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 150, 20));

        text_token.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_token.setBorder(null);
        text_token.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tokenActionPerformed(evt);
            }
        });
        text_token.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_tokenKeyReleased(evt);
            }
        });
        getContentPane().add(text_token, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 388, 320, 50));

        text_username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_username.setBorder(null);
        text_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 290, 320, 50));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close-eyeres.png"))); // NOI18N
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 40, 40));

        text_passfield.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        text_passfield.setBorder(null);
        text_passfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                text_passfieldMouseExited(evt);
            }
        });
        text_passfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_passfieldKeyReleased(evt);
            }
        });
        getContentPane().add(text_passfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 486, 276, 48));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/arrow.png"))); // NOI18N
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_backMouseExited(evt);
            }
        });
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 40, 40));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("KEMBALI");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 80, 20));

        btn_mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mulaiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Lupa Password.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameActionPerformed

    private void text_tokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tokenActionPerformed

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
        if(jToggleButton1.isSelected()){
            text_passfield.setEchoChar((char)0);
            this.jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/eyeres.png")));
        }else{
            text_passfield.setEchoChar('*');
            this.jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/close-eyeres.png")));
        }
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btn_mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mulaiActionPerformed
         String userUser = this.text_username.getText(),
                 tokenUser = this.text_token.getText(),
                 passUser = this.text_passfield.getText();
        try {
            String sql = "SELECT * FROM akun WHERE username = '" + userUser + "' " + "AND token = '" + tokenUser + "' ";
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
                String userAkun = r.getString("username");
               String tokenAkun = r.getString("token");
                        
                if(userAkun.equals(userUser) && tokenAkun.equals(tokenUser)){
                    
                    // remake token
                    String rand = "abcdefghijklmnopqrstuvwxyz".toUpperCase();
                    int range = (rand.length()) ;
                    String Result = "";
                    for (int i = 0; i < 6; i++) {
                    int getValue = (int)(Math.random() * range);
                    char CharPoss = rand.charAt(getValue);
                    Result += CharPoss;
                }
                    
                    // execute update
                    String passUserEncrypt = BCrypt.hashpw(passUser, BCrypt.gensalt(10));
                    String upsql = "UPDATE  akun SET pass = '"+ passUserEncrypt +"', token = '" + Result +"' WHERE username = '"+ userUser +"' ";
                    s.executeUpdate(upsql);
                    this.text_username.setText("");
                    this.text_token.setText("");
                    this.text_passfield.setText("");
                    JOptionPane.showMessageDialog(this, "password berhasil diubah");
                    try {
                        TimeUnit.SECONDS.sleep(2);
                        new LoginFrame().setVisible(true);
                        dispose();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LupapassFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }else{
                    JOptionPane.showMessageDialog(this, "token salah");
                    System.out.println("salahhh");
                }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btn_mulaiActionPerformed

    private void text_tokenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_tokenKeyReleased
        int pos = text_token.getCaretPosition();
        text_token.setText(text_token.getText().toUpperCase());
        text_token.setCaretPosition(pos);
    }//GEN-LAST:event_text_tokenKeyReleased

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_backMouseEntered

    private void btn_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btn_backMouseExited

    static String punyanumber;
    
    private void text_passfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_passfieldKeyReleased
        String fieldPass = this.text_passfield.getText();
        char[] chars = fieldPass.toCharArray();
        punyanumber = "";
        for(char c : chars){
            if(Character.isDigit(c)){
                punyanumber = "yes";
            }
        }
        
        if(fieldPass.length() > 8 && !fieldPass.equals(fieldPass.toLowerCase()) && punyanumber.equals("yes")){
                this.weakness.setText("STRONG");
                weakness.setForeground(Color.green);
        }
        else if (this.text_passfield.getText().length() > 7){
                this.weakness.setText("BAGUS");
                weakness.setForeground(Color.blue);
            }else if(this.text_passfield.getText().length() > 5){
                this.weakness.setText("SEDANG");
                weakness.setForeground(Color.yellow);
            }else{
                this.weakness.setText("LEMAH");
                weakness.setForeground(Color.red);
            }
    }//GEN-LAST:event_text_passfieldKeyReleased

    private void text_passfieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_passfieldMouseExited
        this.weakness.setText("");
    }//GEN-LAST:event_text_passfieldMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupapassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupapassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupapassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupapassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupapassFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_mulai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField text_passfield;
    private javax.swing.JTextField text_token;
    private javax.swing.JTextField text_username;
    private javax.swing.JLabel weakness;
    // End of variables declaration//GEN-END:variables
}
