/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package base;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Pramudya
 */
public class testingFrame extends javax.swing.JFrame {

    /** Creates new form testingFrame */
    public testingFrame() {
        initComponents();
        showLineChart();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelLineChart = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 153));
        jLabel1.setText("Rp 0");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 250, 40));

        jButton1.setText("teswkwk");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 50));

        jButton2.setText("pengeluaran");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 120, 50));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 160, 70));

        panelLineChart.setBackground(new java.awt.Color(255, 153, 204));
        panelLineChart.setLayout(new javax.swing.BoxLayout(panelLineChart, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(panelLineChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 460, 280));

        jLabel2.setText("wkwkwkwkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkwkwkw");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showLineChart(){
        // get value how much transaction sell has done
           Date harisekarang = new Date();
        SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd");
        String nowDate = ft.format(harisekarang);
        
        LocalDate harinii = LocalDate.now();
        
//            String arrTgl[] = new String[7];
//            int arrJumlah[] = new int[7];
         
            String hasiltanggal[] = new String[7];
            String hasilbulan[] = new String[7];
            
            String tanggalrealtime[] = new String[7];
//            String bulanrealtime[] = new String[7];

            for (int i = 0; i < tanggalrealtime.length; i++) {
                tanggalrealtime[i] = "s";
                harinii.plusDays(-7);
        }
            
            for (int i = 0; i < 7; i++) {
            String hasilnyaa = tanggalrealtime[i];
            try {
            String getSQL = String.format("SELECT DAY(tgl_penjualan) AS haritgl, MONTH(tgl_penjualan) AS motgl, COUNT(kode_penjualan) AS jumlah_transaksi\n" +
                "FROM `penjualan` WHERE DATE(tgl_penjualan) = %s GROUP BY DATE(tgl_penjualan)", hasilnyaa);
             Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery(getSQL);
//            ResultSet rs = s.executeQuery("SELECT DATE(tgl_penjualan)-1 AS tanggal, COUNT(kode_penjualan) AS jumlah_transaksi, DAY(tgl_penjualan) AS haritgl, MONTH(tgl_penjualan) AS motgl \n" +
//"FROM `penjualan` getLastRecord\n" +
//"GROUP BY tanggal\n" +
//"ORDER BY `kode_penjualan` DESC  LIMIT 7");
//            
            while (rs.next()){
                String tglTrans = rs.getString("haritgl"),
                        mntTrans = rs.getString("motgl");
                
//                hasiltanggal[i] = tglTrans;
            }
//            int i = 0;
//            while (rs.next()) {
//                String idJumlah = rs.getString("jumlah_transaksi"),
//                        tglTrans = rs.getString("haritgl"),
//                        mntTrans = rs.getString("motgl");
//                arrJumlah[i] = Integer.parseInt(idJumlah);
//                arrTgl[i] = tglTrans + "/" + mntTrans;
//                i++;
//            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error : " + ex.getMessage());
        }
            
        }
        //create dataset for the graph
         DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//        dataset.setValue(arrJumlah[6], "Amount", arrTgl[6]);
//        dataset.setValue(arrJumlah[5], "Amount", arrTgl[5]);
//        dataset.setValue(arrJumlah[4], "Amount", arrTgl[4]);
//        dataset.setValue(arrJumlah[3], "Amount", arrTgl[3]);
//        dataset.setValue(arrJumlah[2], "Amount", arrTgl[2]);
//        dataset.setValue(arrJumlah[1], "Amount", arrTgl[1]);
//        dataset.setValue(arrJumlah[0], "Amount", arrTgl[0]);
        
        //create chart
        JFreeChart linechart; 
        linechart = ChartFactory.createLineChart("grafik jumlah transaksi","harian","jumlah", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        //create plot object
         CategoryPlot lineCategoryPlot;
        lineCategoryPlot = linechart.getCategoryPlot();
       // lineCategoryPlot.setRangeGridlinePaint(Color.BLUE);
        lineCategoryPlot.setBackgroundPaint(java.awt.Color.WHITE);
        
        //create render object to change the moficy the line properties like color
        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) lineCategoryPlot.getRenderer();
//        Color lineChartColor;
//        lineChartColor = new Color(204,0,51);
        lineRenderer.setSeriesPaint(0, java.awt.Color.BLACK);
        
         //create chartPanel to display chart(graph)
        ChartPanel lineChartPanel = new ChartPanel(linechart);
        panelLineChart.removeAll();
        panelLineChart.add(lineChartPanel, BorderLayout.CENTER);
        panelLineChart.validate();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date harisekarang = new Date();
       SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd");
       String hariinicuy = ft.format(harisekarang); 
       
        try{
            String sql = "SELECT tgl_penjualan, SUM(total) AS total_harga FROM `penjualan` getLastRecord WHERE  DATE(tgl_penjualan) = '"+hariinicuy+"' GROUP BY DATE(tgl_penjualan)" ;
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
                String jumlahPendapatan = r.getString("total_harga");
                int jpRes = Integer.parseInt(jumlahPendapatan);
                DecimalFormat formatter = new DecimalFormat("#,###");
                this.jLabel1.setText("Rp "+ formatter.format(jpRes));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date harisekarang = new Date();
       SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd");
       String hariinicuy = ft.format(harisekarang); 
       
        try{
            String sql = "SELECT tgl_pembelian, SUM(total_beli) AS total_harga FROM `pembelian` getLastRecord WHERE  DATE(tgl_pembelian) = '"+hariinicuy+"' GROUP BY DATE(tgl_pembelian)" ;
            Connection c = (Connection) koneksi.configDB();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
                String jumlahPendapatan = r.getString("total_harga");
                int jpRes = Integer.parseInt(jumlahPendapatan);
                DecimalFormat formatter = new DecimalFormat("#,###");
                this.jLabel1.setText("Rp "+ formatter.format(jpRes));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "kamu yakin ingin menghapusnya?", "konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION){
            System.out.println("kamu memilih ya");
        }
        else if (response == JOptionPane.NO_OPTION){
            System.out.println("tidak jadi hehe");
        }
        else if (response == JOptionPane.CLOSED_OPTION){
            System.out.println("opsi di tutup");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelLineChart;
    // End of variables declaration//GEN-END:variables

}
